[package]
name = "discord-bot"
version = "0.1.0"
edition = "2018"

[dependencies]
tokio = { version = "0.2", features = ["full"] }
serenity =  { default-features = false, features = ["client", "gateway", "model", "rustls_backend"], version = "0.9.0-rc.2"}
